---
version: "3.4"
services:
  postgres:
    image: "postgres:13-alpine"
    env_file:
      - "dev.env"
      - "creds.env"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - "dev.env"
      - "creds.env"
    ports:
      - "6379:6379"
  vault:
    image: "vault:latest"
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=nautobot"
      - "VAULT_ADDR=http://0.0.0.0:8200"
      - "VAULT_TOKEN=nautobot"
    cap_add:
      - "IPC_LOCK"
    ports:
      - "8200:8200"
volumes:
  postgres_data: {}
