# Generated by Django 3.2.25 on 2024-06-26 14:32

from django.db import migrations


def update_secret_provider_slug(apps, schema_editor):
    Secret = apps.get_model("extras", "Secret")
    Secret.objects.filter(provider="thycotic-tss-id").update(provider="delinea-tss-id")
    Secret.objects.filter(provider="thycotic-tss-path").update(provider="delinea-tss-path")


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(update_secret_provider_slug),
    ]
