from nautobot_secrets_providers.providers import AWSSecretsManagerSecretsProvider, HashiCorpVaultSecretsProvider

secrets_providers = [AWSSecretsManagerSecretsProvider, HashiCorpVaultSecretsProvider]
